<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <PublishAot>true</PublishAot>
      <IsAotCompatible>true</IsAotCompatible>
      <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    </PropertyGroup>
  
  <PropertyGroup>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Org.Grush.HomeBase.WeatherStationLib.SEN0658\Org.Grush.HomeBase.WeatherStationLib.SEN0658.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tasks">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
