<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <IsAotCompatible>true</IsAotCompatible>
        <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
        <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentModbus" />
      <PackageReference Include="System.Device.Gpio" />
    </ItemGroup>
    
    <ItemGroup>
<!--      <ClCompile Include="dfrobot-example.cpp" />-->
    </ItemGroup>

</Project>
