<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
      <PublishAot>true</PublishAot>
      <IsAotCompatible>true</IsAotCompatible>
      <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentModbus" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="System.Device.Gpio" />
      <PackageReference Include="System.IO.Ports" />
    </ItemGroup>

</Project>
